server:
  port: ${SERVER_PORT:8086}

spring:
  application:
    name: id-generator-service

snowflake:
  machine-id: ${SNOWFLAKE_MACHINE_ID:1}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always
